import {
  Home,
  Building,
  MapPin,
  Zap,
  Car,
  Menu,
  X,
  Plus,
  ChevronLeft,
  Settings,
  Sun,
  Moon,
  Monitor,
  Edit,
  Trash2,
  Calendar,
  Filter,
  ChevronDown,
  DollarSign,
  TrendingUp,
  Activity,
  CheckCircle,
  XCircle,
  AlertTriangle,
  Info,
  Bell,
  Wrench,
  type LucideProps
} from 'lucide-react';
import { type IconName } from '../types/shared-types';

export const iconMap: Record<IconName, React.FC<LucideProps>> = {
  home: Home,
  building: Building,
  'map-pin': MapPin,
  zap: Zap,
  car: Car,
  menu: Menu,
  x: X,
  plus: Plus,
  'chevron-left': ChevronLeft,
  settings: Settings,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  edit: Edit,
  'trash-2': Trash2,
  calendar: Calendar,
  filter: Filter,
  'chevron-down': ChevronDown,
  'dollar-sign': DollarSign,
  'trending-up': TrendingUp,
  activity: Activity,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  'alert-triangle': AlertTriangle,
  info: Info,
  bell: Bell,
  wrench: Wrench
};
